Recruitment_4AD/Recruitment_4AD/recruit/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from  django.conf.urls import  url,include
from django.conf import  settings
from Condidate import  views as condidatesViews
from accounts import  views as accountsViews
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^recruitment',condidatesViews.home,name='Home'),
    url(r'^candidates/apply/$', condidatesViews.apply, name='candidate_apply'),
    url(r'^candidates/apply/success/$', condidatesViews.apply_success, name='candidate_apply_success'),
    url(r'^login',accountsViews.userlogin,name='login'),
    url(r'^detail/(?P<id_num>\d+)/$', condidatesViews.detail, name='detail'),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Recruitment_4AD/Recruitment_4AD/Condidate/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django_countries.fields import CountryField
from recruit.choices import (EDUCATION_CHOICES, EMPLOYER_TYPE_CHOICES)

class Candidate(models.Model):
	first_name=models.CharField(max_length=30, blank=False)
	last_name = models.CharField(max_length=30, blank=False)
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	birth_year = models.CharField(max_length=4, blank=False)
	date_of_birth = models.DateField(blank=True, null=True)
	gender = models.CharField(choices=(('male', 'Male'), ('female', 'Female'),), max_length = 10, blank=True, null=True)
	education = models.CharField(
			max_length=25,
			blank=True,
			choices=EDUCATION_CHOICES,
		)	
	education_major = models.CharField(max_length=250, blank=True)
	current_location = CountryField(blank=True)
	image = models.ImageField(upload_to='employer/%Y/%m/%d')
	thumb = models.ImageField(upload_to='employer/%Y/%m/%d', blank=True)
	is_active = models.BooleanField(default=False)
	last_modified = models.DateTimeField(auto_now_add=False, auto_now=True)
	created = models.DateTimeField(auto_now_add=True, auto_now=False)

	def save(self, *args, **kwargs):
		from recruit.utils import generate_thumbnail
		self.thumb = generate_thumbnail(self.image)
		super(Candidate, self).save(*args, **kwargs)

	def delete(self, *args, **kwargs):
		from recruit.utils import delete_from_s3
		delete_from_s3([self.image, self.thumb])
		super(Candidate, self).delete(*args, **kwargs)	


	def __str__(self):
		return self.user.email

def update_user_profile(sender, instance, created, **kwargs):
	from accounts.models import UserProfile
	if created:
		UserProfile.objects.filter(user=instance.user).update(user_type='Candidate')

post_save.connect(update_user_profile, sender=Candidate)		

class CandidateRequirements(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	# location = models.ManyToManyField(Location, on_delete=models.CASCADE)  create m2m
	employer_type = models.CharField(
			max_length=25,
			blank=True,
			choices=EMPLOYER_TYPE_CHOICES,
		)

class CandidateDocument(models.Model):
	candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)
	document = models.FileField(upload_to='candidate/%Y/%m/%d')	
	document_type = models.CharField(max_length=50)
	is_active = models.BooleanField(default=1)
	last_modified = models.DateTimeField(auto_now_add=False, auto_now=True)
	created = models.DateTimeField(auto_now_add=True, auto_now=False)

	def delete(self, *args, **kwargs):
		from recruit.utils import delete_from_s3
		delete_from_s3([self.document])
		super(CandidateDocument, self).delete(*args, **kwargs)

Recruitment_4AD/Recruitment_4AD/Condidate/forms.py
from django import forms
from django_countries.fields import LazyTypedChoiceField
from django_countries import countries
from recruit.choices import (TIMEZONE_CHOICES, EDUCATION_CHOICES,
	 GENDER_CHOICES)

class UserApplyStep1Form(forms.Form):
	first_name = forms.CharField(max_length=20)
	last_name = forms.CharField(max_length=20)
	email = forms.EmailField(max_length=50)
	citizenship = LazyTypedChoiceField(choices=countries)
	skype_id = forms.CharField(label='Skype ID', max_length=20)
	timezone = forms.ChoiceField(choices=TIMEZONE_CHOICES)
	birth_year = forms.IntegerField(min_value=1950, max_value=2000)
	gender = forms.TypedChoiceField(choices=GENDER_CHOICES)
	education = forms.TypedChoiceField(choices=EDUCATION_CHOICES)
	education_major = forms.CharField(max_length=50)

class UserApplyStep2Form(forms.Form):
	image = forms.ImageField()
	resume = forms.FileField()

Recruitment_4AD/Recruitment_4AD/Condidate/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import redirect
from accounts.models import UserProfile
from .forms import UserApplyStep1Form, UserApplyStep2Form
from django.contrib import messages
from django.contrib.auth.models import User
from .models import Candidate, CandidateDocument


@csrf_exempt
def home(request):
    if request.method=='POST':
        if request.POST.get("Apply"):
            return redirect('candidates/apply/')
        elif request.POST.get("Login"):
            return redirect('login')

    else:
        return render_to_response('Condidate/Home.html')


def apply(request):
    key = request.GET.get('key', None)
    user = UserProfile.verify_token(key)

    if not key and request.method == 'POST':

        form = UserApplyStep1Form(request.POST)

        if form.is_valid():
            data = form.data
            first_name = data['first_name']
            last_name = data['last_name']
            email = data['email']
            citizenship = data['citizenship']
            skype_id = data['skype_id']
            timezone = data['timezone']
            birth_year= data['birth_year']
            gender=data['gender']
            education = data['education']
            education_major = data['education_major']

            user, created = User.objects.get_or_create(
                first_name=first_name,
                last_name=last_name,
                email=email,
                username=email
            )

            if not created:
                messages.add_message(request, messages.ERROR,
                                     email + ' has already been registered.')
            else:
                userprofile = UserProfile(
                    first_name=first_name,
                    last_name=last_name,
                    user=user,
                    timezone=timezone,
                    citizenship=citizenship,
                    skype_id=skype_id,
                    user_type='Candidate',
                    birth_year=birth_year,
                    gender=gender,
                    education=education,
                    education_major=education_major
                )

                userprofile.save()

                key = user.userprofile.generate_token()

                return HttpResponseRedirect(
                    reverse('candidate_apply') + '?key=' + key)


    elif not key and request.method == 'GET':
        form = UserApplyStep1Form()

    elif key and user and request.method == 'POST':

        form = UserApplyStep2Form(request.POST, request.FILES)

        if form.is_valid():
            files = form.files
            data = form.data

            try:
                candidate = user.candidate
                candidate.image = files['image']
                candidate.save()
            except Candidate.DoesNotExist:
                candidate = Candidate.objects.create(user=user,
                                                     image=files['image']
                                                     )
            CandidateDocument.objects.create(
                candidate=candidate,
                document=files['resume'],
                document_type='Resume'
            )

            messages.add_message(request, messages.SUCCESS,
                                 'Form submitted successfully.')

            return HttpResponseRedirect(
                reverse('candidate_apply_success') + '?key=' + key)

    elif key and user and request.method == 'GET':
        form = UserApplyStep2Form()

    else:
        messages.add_message(request, messages.ERROR,
                             'A valid application key is required to submit documents. ' +
                             'Please contact the administrator.')
        form = None

    return render(request, 'Condidate/apply.html', {'form': form,'done':'done'})


def apply_success(request):
    key = request.GET.get('key', None)
    user = UserProfile.verify_token(key)

    if not key or not user:
        messages.add_message(request, messages.ERROR,
                             'A valid application key is required to view this page.')


    return render(request, 'Condidate/apply.html',
                  {'success': 'success'
                   })

@csrf_exempt
def detail(request,id_num):

    if request.method=='POST':
        if request.POST.get("Accept"):
            UserProfile.objects.filter(id=id_num).update(is_active=True)
            candi = UserProfile.objects.all()
            return render(request, 'Condidate/details.html',
                          {'success': 'success','candi': candi,'id_num':id_num
                           })
        elif request.POST.get("Reject"):

            UserProfile.objects.filter(id=id_num).delete()
            candi = UserProfile.objects.all()
            context = {'candidate': candi}
            return render(request, 'Condidate/details.html', context)
    else:
        User_list = UserProfile.objects.filter(id=id_num)

        context = {'details': User_list}
        return render(request, 'Condidate/list_details.html', context)

Recruitment_4AD/Recruitment_4AD/Condidate/templates/Condidate/Home.html
{% extends 'base.html' %}

{% block head %}
{{ block.super }}

{% include 'Condidate/_progress_style.html' %}

{% endblock %}

{% block content %}

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <h1><center><p style="color:DodgerBlue;">Welcome to Requirment Site</p></center></h1>
    <h2><center><p style="color:DodgerBlue;">Click on Apply if you wanna Apply for the Opening. Login for Admin Only</p></center></h2>

    <style>
        	.myButton {
	background-color: #72f7e4;
    -moz-border-radius: 28px;
    -webkit-border-radius: 28px;
    border-radius: 108px;
    display: inline-block;
    cursor: pointer;
    color: #ffffff;
    font-family: Arial;
    font-size: 17px;
    font-weight: bold;
    padding: 8px 89px;
    text-decoration: none;
    margin-left: 80px;
}
.myButton:hover {
	background-color:#5cbf2a;
}
.myButton:active {
	position:relative;
	top:1px;
}
    </style>

</head>
<body>
<form action="{% url 'Home' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <br><br><br>
            <center>
            <button type="submit" class="myButton" name="Apply" value="Apply">&nbsp;Apply</button>
            <button type="submit" name="Login" class="myButton" value="Login">&nbsp;Login</button>
                </center>
        </form>
</body>
{% endblock %}

Recruitment_4AD/Recruitment_4AD/Condidate/templates/Condidate/_progress_style.html
<style>
.bs-wizard {margin-top: 40px;}

/*Form Wizard*/
.bs-wizard {border-bottom: solid 1px #e0e0e0; padding: 0 0 10px 0;}
.bs-wizard > .bs-wizard-step {padding: 0; position: relative;}
.bs-wizard > .bs-wizard-step + .bs-wizard-step {}
.bs-wizard > .bs-wizard-step .bs-wizard-stepnum {color: #595959; font-size: 16px; margin-bottom: 5px;}
.bs-wizard > .bs-wizard-step .bs-wizard-info {color: #999; font-size: 14px;}
.bs-wizard > .bs-wizard-step > .bs-wizard-dot {position: absolute; width: 30px; height: 30px; display: block; background: #fbe8aa; top: 45px; left: 50%; margin-top: -15px; margin-left: -15px; border-radius: 50%;} 
.bs-wizard > .bs-wizard-step > .bs-wizard-dot:after {content: ' '; width: 14px; height: 14px; background: #fbbd19; border-radius: 50px; position: absolute; top: 8px; left: 8px; } 
.bs-wizard > .bs-wizard-step > .progress {position: relative; border-radius: 0px; height: 8px; box-shadow: none; margin: 20px 0;}
.bs-wizard > .bs-wizard-step > .progress > .progress-bar {width:0px; box-shadow: none; background: #fbe8aa;}
.bs-wizard > .bs-wizard-step.complete > .progress > .progress-bar {width:100%;}
.bs-wizard > .bs-wizard-step.active > .progress > .progress-bar {width:50%;}
.bs-wizard > .bs-wizard-step:first-child.active > .progress > .progress-bar {width:0%;}
.bs-wizard > .bs-wizard-step:last-child.active > .progress > .progress-bar {width: 100%;}
.bs-wizard > .bs-wizard-step.disabled > .bs-wizard-dot {background-color: #f5f5f5;}
.bs-wizard > .bs-wizard-step.disabled > .bs-wizard-dot:after {opacity: 0;}
.bs-wizard > .bs-wizard-step:first-child  > .progress {left: 50%; width: 50%;}
.bs-wizard > .bs-wizard-step:last-child  > .progress {width: 50%;}
.bs-wizard > .bs-wizard-step.disabled a.bs-wizard-dot{ pointer-events: none; }
/*END Form Wizard*/	
</style>

Recruitment_4AD/Recruitment_4AD/Condidate/templates/Condidate/apply.html
{% extends 'base.html' %}

{% block head %}
{{ block.super }}

{% endblock %}

{% block content %}
<style>
    input[type=text] ,input[type=password],input[type="email"]  {
   	 	width: 30%;
    	padding: 22px 60px;
    	margin: 7px 60px;
    	box-sizing: border-box;
    	border: none;
    	outline: none;
    	border-bottom: 2px solid #0000002e;
	}
	select {
	    width: 30%;
    	padding: 22px 60px;
    	margin: 7px 60px;
    	box-sizing: border-box;
    	border: none;
    	outline: none;
    	border-bottom: 2px solid #0000002e;
	}

	.myButton {
	background-color: #72f7e4;
    -moz-border-radius: 28px;
    -webkit-border-radius: 28px;
    border-radius: 108px;
    display: inline-block;
    cursor: pointer;
    color: #ffffff;
    font-family: Arial;
    font-size: 17px;
    font-weight: bold;
    padding: 8px 89px;
    text-decoration: none;
    margin-left: 80px;
}

</style>
{% if form %}
<h1>Application Page</h1>
<form method='post' enctype="multipart/form-data">
{% csrf_token %}
{% for field in form %}
    <div class="fieldWrapper">
        {{ field.label_tag }} {{ field }}
        {{ field.errors }}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
        <script>
    $('#step2').addClass('complete');
</script>
    </div>
{% endfor %}
    <br><br>
<input type='submit' class="myButton" value='Next'>
</form>
{% endif %}

{% if done %}
<script>
    $('#step2').addClass('complete');
</script>

{% endif %}
{% if success %}
<h1>Congratulations! <small>Application Submitted</small></h1>
<div class='row'>
    <div class='col-md-offset-3 col-md-6'>
        <h3>What next?</h3>
        <p>Your application materials have been received and our being reviewed.

    </div>
</div>
{% endif %}

{{ block.super }}
<script>
    $('#step1').addClass('complete');
</script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.6/jstz.min.js"></script>
<script>
	var timezoneValues = Object.values(jstz.olson.timezones);
	var detectedTimezone = jstz.determine().name();
	if(timezoneValues.indexOf(detectedTimezone) != -1) {
	  $('#id_timezone').prop('selected', true).val(detectedTimezone);
	}
</script>
{% endblock %}

Recruitment_4AD/Recruitment_4AD/Condidate/templates/Condidate/dashboard.html
{% extends "base.html" %}
<div class='row'>
	<div class='col-xs-12 col-sm-6'>
		<h2>Overview</h2>
		<ul class="list-group">
			<li class="list-group-item">
				<a href='#'><span class="badge">18</span>
					Interviews Pending Confirmation
				</a>
			</li>
			<li class="list-group-item">
				<a href='#'><span class="badge">15</span>
					Interviews Awaiting Follow Up
				</a>
			</li>			
			<li class="list-group-item">
				<a href='#'><span class="badge">14</span>
					New Jobs
				</a>
			</li>
			<li class="list-group-item">
				<a href='#'><span class="badge">20</span>
					...
				</a>
			</li>
		</ul>
	</div>
	<div class='col-xs-12 col-sm-6'>
		<h2>Actions</h2>
		<ul class="list-group">
			<li class="list-group-item">
				<a href='#'>
					Update Preferences
				</a>
			</li>
			<li class="list-group-item">
				<a href='#'>
					Update Resume
				</a>
			</li>			
			<li class="list-group-item">
				<a href='#'>
					Update Availability
				</a>
			</li>
			<li class="list-group-item">
				<a href='#'>
					...
				</a>
			</li>
		</ul>		
	</div>
</div>

Recruitment_4AD/Recruitment_4AD/Condidate/templates/Condidate/details.html
{% extends 'base.html' %}

{% block head %}
{{ block.super }}

{% include 'Condidate/_progress_style.html' %}

{% endblock %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        img.disabled {
            opacity:0.5;
         }
    </style>
</head>
<body>
<p align="center" style="color:DodgerBlue;" ><strong>Please click on Specific link to view the Candidate details and you the accept and reject the same</strong></p><br><br>
<table border="1" align="center">

    <tr>
        <th>ID</th>
        <th>Link To view the Details</th>
        <th>Application status</th>
    </tr>

    {% for item in candidate %}
    <tr>

        <td><label>{{ item.id }}</label></td>
        <td><a href="{% url 'detail' item.id %}">{{ item.user }}</a></td>
        {% if item.is_active%}
            <td><label>Accepted</label></td>
        {% else %}
            <td><label>Pending</label></td>
        {% endif %}
    </tr>
    {% endfor %}

    {% if success %}
        {% for item in candi %}
        <tr>

        <td><label>{{ item.id }}</label></td>
        <td><a href="{% url 'detail' item.id %}">{{ item.user }}</a></td>
        {% if item.is_active%}
            <td><label>Accepted</label></td>
        {% else %}
            <td><label>Pending</label></td>
        {% endif %}
        </tr>

    {% endfor %}
   <center> <h2>Congratulations! <small>Application Got Accepted </small></h2>
<div class='row'>
    <div class='col-md-offset-3 col-md-6'>
        <h3>Thanks Alot for applying </h3>
        <p>Your application materials have been received and our being reviewed.

    </div>
</div>
        </center>
{% endif %}

</table>
</body>
{% endblock %}

Recruitment_4AD/Recruitment_4AD/Condidate/templates/Condidate/list_details.html
{% extends 'base.html' %}

{% block head %}
{{ block.super }}

{% include 'Condidate/_progress_style.html' %}

{% endblock %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
    .div_1 {
    border: 1px solid black;
    margin: 25px 50px 75px 100px;
    background-color: lightgreen;
}

	.myButton {
	background-color: #72f7e4;
    -moz-border-radius: 28px;
    -webkit-border-radius: 28px;
    border-radius: 108px;
    display: inline-block;
    cursor: pointer;
    color: #ffffff;
    font-family: Arial;
    font-size: 17px;
    font-weight: bold;
    padding: 8px 89px;
    text-decoration: none;
    margin-left: 80px;
}
.myButton:hover {
	background-color:#5cbf2a;
}
.myButton:active {
	position:relative;
	top:1px;
}
    </style>
</head>
<body>

   <h2 style="color:DodgerBlue;">Congratulations! <small>Please Find out the Details given below </small></h2>
    <h3 style="color:DodgerBlue;">Review the Details and Accept or Reject </h3><br><br>
<div class='row'>
    <div class='col-md-offset-3 col-md-6'>


    </div>
</div>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

{% for item in details %}
    <div class="div_1">
    <br><br>
    <label>First Name       : {{item.first_name}} </label><br>
    <label>Last Name        : {{item.last_name}} </label><br>
    <label>Email ID          : {{item.user}} </label><br>
    <label>CitizenShip      : {{item.citizenship}} </label><br>
    <label>Type of user     : {{item.user_type}} </label><br>
    <label>Skype ID         : {{item.skype_id}} </label><br>
    <label>Birth year     : {{item.birth_year}} </label><br>
    <label>gender    : {{item.gender}} </label><br>
    <label>education    : {{item.education}} </label><br>
    <label>Education major    : {{item.education_major}} </label><br>
    <label>Created Date     : {{item.created}} </label><br>
    <label>ModificationDate : {{item.last_modified}} </label><br>
    <label>TimeZone         : {{item.timezone}} </label>
    </div>
    {% endfor %}

            <button type="submit" name="Accept" class="myButton" value="Accept">&nbsp;Accept</button>
            <button type="submit" name="Reject" class="myButton" value="Reject">&nbsp;Reject</button>

        </form>



</body>

{% endblock %}